theme: jekyll-theme-hacker

title: Open source legal tech
description: "One of our projects: AI native Word redlining and playbook generation."

github:
  is_project_page: false
  repository_url: https://github.com/yuch85/contract-playbook-ai

plugins:
  - jekyll-include-cache
